-- Les cours réels du club bloquent la location (Eddy, 01/10/2026 : « que les heures
-- du planning correspondent aux vraies heures — balayage complet »).
--
-- Avant cette migration, seules 24 règles existaient : mercredi et samedi
-- 15h–17h « éducative », partout. Le vrai planning de la rentrée 2026
-- (Plannings/bc-plannings/src/data/plannings.js, 219 cours hors été) en impose
-- bien plus : 181 heures étaient EN VENTE alors qu'un cours occupait la salle.
--
-- Règle de calcul : un créneau coach (heure pleine, départ 10h→18h) est bloqué
-- dès qu'un cours le chevauche, même d'une demi-heure (12h30–13h30 bloque 12h
-- ET 13h). « ACCES LIBRE » n'est pas un cours — c'est la salle ouverte aux
-- adhérents, le moment même où un coach y travaille — il ne bloque rien.
-- Portet : le planning provisoire ET celui des deux salles s'appliquent, faute
-- de date de bascule connue ; l'union ne vend jamais une heure occupée.
-- Les 24 règles « éducative » existantes (cahier) sont conservées.
--
-- Fichier généré depuis le planning ; idempotent (on conflict do update).

insert into public.coach_slot_block_rules (club_id, space_id, isodow, start_hour, reason)
values
  ('etats-unis', 'boxe', 1, 12, 'cours : BOXE PIEDS POINGS'),
  ('etats-unis', 'boxe', 1, 13, 'cours : BOXE PIEDS POINGS'),
  ('etats-unis', 'boxe', 1, 18, 'cours : BOXE PIEDS POINGS'),
  ('etats-unis', 'boxe', 2, 12, 'cours : BOXE ANGLAISE'),
  ('etats-unis', 'boxe', 2, 13, 'cours : BOXE ANGLAISE'),
  ('etats-unis', 'boxe', 2, 18, 'cours : BOXE ANGLAISE'),
  ('etats-unis', 'boxe', 3, 12, 'cours : BOXE PIEDS POINGS'),
  ('etats-unis', 'boxe', 3, 13, 'cours : BOXE PIEDS POINGS'),
  ('etats-unis', 'boxe', 3, 15, 'cours : BOXE PIEDS POINGS 7/11 ANS'),
  ('etats-unis', 'boxe', 3, 16, 'cours : BOXE PIEDS POINGS 12/16 ANS'),
  ('etats-unis', 'boxe', 3, 18, 'cours : BOXE PIEDS POINGS'),
  ('etats-unis', 'boxe', 4, 12, 'cours : BOXE ANGLAISE'),
  ('etats-unis', 'boxe', 4, 13, 'cours : BOXE ANGLAISE'),
  ('etats-unis', 'boxe', 4, 18, 'cours : BOXE PIEDS POINGS'),
  ('etats-unis', 'boxe', 5, 18, 'cours : BOXE ANGLAISE'),
  ('etats-unis', 'boxe', 6, 11, 'cours : BOXE ANGLAISE'),
  ('etats-unis', 'boxe', 6, 14, 'cours : BOXE PIEDS POINGS (3/6ANS)'),
  ('etats-unis', 'boxe', 6, 15, 'cours : BOXE PIEDS POINGS 7/11 ANS'),
  ('etats-unis', 'boxe', 6, 16, 'cours : BOXE PIEDS POINGS 12/16 ANS'),
  ('etats-unis', 'fitness', 1, 12, 'cours : HYROX'),
  ('etats-unis', 'fitness', 1, 13, 'cours : HYROX'),
  ('etats-unis', 'fitness', 1, 18, 'cours : HYROX'),
  ('etats-unis', 'fitness', 2, 12, 'cours : BOXING HIIT'),
  ('etats-unis', 'fitness', 2, 13, 'cours : BOXING HIIT'),
  ('etats-unis', 'fitness', 2, 18, 'cours : LADY PUNCH'),
  ('etats-unis', 'fitness', 3, 18, 'cours : LADY PUNCH'),
  ('etats-unis', 'fitness', 4, 12, 'cours : CROSS-TRAINING'),
  ('etats-unis', 'fitness', 4, 13, 'cours : CROSS-TRAINING'),
  ('etats-unis', 'fitness', 4, 18, 'cours : HYROX'),
  ('etats-unis', 'fitness', 5, 12, 'cours : BOXING HIIT'),
  ('etats-unis', 'fitness', 5, 13, 'cours : BOXING HIIT'),
  ('etats-unis', 'fitness', 5, 18, 'cours : LADY PUNCH'),
  ('etats-unis', 'fitness', 6, 11, 'cours : CROSS-TRAINING'),
  ('etats-unis', 'mma-sol', 1, 18, 'cours : JIU-JITSU BRESILIEN'),
  ('etats-unis', 'mma-sol', 2, 18, 'cours : GRAPPLING'),
  ('etats-unis', 'mma-sol', 3, 18, 'cours : ASSO MMA ENFANTS 10/16 ANS'),
  ('etats-unis', 'mma-sol', 4, 18, 'cours : GRAPPLING'),
  ('etats-unis', 'mma-sol', 5, 18, 'cours : JIU-JITSU BRESILIEN'),
  ('etats-unis', 'mma-sol', 6, 18, 'cours : ASSO MMA ENFANTS 10/16 ANS'),
  ('minimes', 'salle', 1, 12, 'cours : BOXING CAMP'),
  ('minimes', 'salle', 1, 13, 'cours : BOXING CAMP'),
  ('minimes', 'salle', 1, 18, 'cours : BOXE COMPÉTITEURS + BOXING LADY'),
  ('minimes', 'salle', 2, 12, 'cours : BOXE ANGLAISE (LOISIRS)'),
  ('minimes', 'salle', 2, 13, 'cours : BOXE ANGLAISE (LOISIRS)'),
  ('minimes', 'salle', 2, 18, 'cours : BOXE COMPÉTITEURS + CROSS-TRAINING'),
  ('minimes', 'salle', 3, 12, 'cours : BOXE ANGLAISE (LOISIRS)'),
  ('minimes', 'salle', 3, 13, 'cours : BOXE ANGLAISE (LOISIRS)'),
  ('minimes', 'salle', 3, 15, 'cours : BOXE EDUCATIVE ENFANTS (7/11ANS)'),
  ('minimes', 'salle', 3, 16, 'cours : BOXE EDUCATIVE ADOS (12/16ANS)'),
  ('minimes', 'salle', 3, 17, 'cours : BOXE EDUCATIVE COMPÉTITEURS'),
  ('minimes', 'salle', 3, 18, 'cours : BOXE EDUCATIVE COMPÉTITEURS + BOXING LADY'),
  ('minimes', 'salle', 4, 12, 'cours : BOXE ANGLAISE (LOISIRS)'),
  ('minimes', 'salle', 4, 13, 'cours : BOXE ANGLAISE (LOISIRS)'),
  ('minimes', 'salle', 4, 18, 'cours : BOXE COMPÉTITEURS + CROSS-TRAINING'),
  ('minimes', 'salle', 5, 12, 'cours : BOXING CAMP'),
  ('minimes', 'salle', 5, 13, 'cours : BOXING CAMP'),
  ('minimes', 'salle', 5, 18, 'cours : BOXE COMPÉTITEURS'),
  ('minimes', 'salle', 6, 11, 'cours : BOXING CAMP'),
  ('minimes', 'salle', 6, 14, 'cours : BABY BOXE (3/6ANS)'),
  ('minimes', 'salle', 6, 15, 'cours : BOXE EDUCATIVE ENFANTS (7/11ANS)'),
  ('minimes', 'salle', 6, 16, 'cours : BOXE EDUCATIVE ADOS (12/16ANS)'),
  ('minimes', 'salle', 6, 17, 'cours : BOXE EDUCATIVE COMPÉTITEURS'),
  ('minimes', 'salle', 6, 18, 'cours : BOXE EDUCATIVE COMPÉTITEURS + OPEN SPARRING'),
  ('portet', 'boxe-fitness', 1, 12, 'cours : ANGLAISE'),
  ('portet', 'boxe-fitness', 1, 13, 'cours : ANGLAISE'),
  ('portet', 'boxe-fitness', 1, 18, 'cours : BOXE EDUCATIVE CONFIRMES'),
  ('portet', 'boxe-fitness', 2, 12, 'cours : PREPARATION PHYSIQUE'),
  ('portet', 'boxe-fitness', 2, 13, 'cours : PREPARATION PHYSIQUE'),
  ('portet', 'boxe-fitness', 2, 16, 'cours : ANGLAISE LOISIRS'),
  ('portet', 'boxe-fitness', 2, 18, 'cours : LADY KICK + BOXE AMATEURS ET PROS'),
  ('portet', 'boxe-fitness', 3, 12, 'cours : KICK / K1'),
  ('portet', 'boxe-fitness', 3, 13, 'cours : KICK / K1'),
  ('portet', 'boxe-fitness', 3, 14, 'cours : KICK ENFANTS'),
  ('portet', 'boxe-fitness', 3, 15, 'cours : KICK ADOS'),
  ('portet', 'boxe-fitness', 3, 16, 'cours : BOXE EDUCATIVE 7/11ANS'),
  ('portet', 'boxe-fitness', 3, 17, 'cours : BOXE EDUCATIVE 12/16ANS'),
  ('portet', 'boxe-fitness', 3, 18, 'cours : BOXING LADY + LADY BOXING'),
  ('portet', 'boxe-fitness', 4, 12, 'cours : ANGLAISE'),
  ('portet', 'boxe-fitness', 4, 13, 'cours : ANGLAISE'),
  ('portet', 'boxe-fitness', 4, 18, 'cours : LADY KICK + BOXE AMATEURS ET PROS'),
  ('portet', 'boxe-fitness', 5, 12, 'cours : SPARRING ANGLAISE ET KICK + ANGLAISE'),
  ('portet', 'boxe-fitness', 5, 13, 'cours : SPARRING ANGLAISE ET KICK + ANGLAISE'),
  ('portet', 'boxe-fitness', 5, 18, 'cours : BOXE AMATEURS ET PROS'),
  ('portet', 'boxe-fitness', 6, 10, 'cours : BOXE FRANCAISE + KICK ENFANTS + BOXE AMATEURS ET PROS'),
  ('portet', 'boxe-fitness', 6, 11, 'cours : PREPARATION PHYSIQUE + KICK ADOS + BOXE AMATEURS ET PROS'),
  ('portet', 'boxe-fitness', 6, 12, 'cours : ANGLAISE'),
  ('portet', 'boxe-fitness', 6, 13, 'cours : ANGLAISE'),
  ('portet', 'boxe-fitness', 6, 15, 'cours : BABY BOXE 4/6 ANS + BABY BOXE (3/6ANS)'),
  ('portet', 'boxe-fitness', 6, 16, 'cours : BOXE EDUCATIVE 7/11ANS'),
  ('portet', 'boxe-fitness', 6, 17, 'cours : BOXE EDUCATIVE 12/16ANS'),
  ('portet', 'mma-sol', 1, 12, 'cours : ANGLAISE'),
  ('portet', 'mma-sol', 1, 13, 'cours : ANGLAISE'),
  ('portet', 'mma-sol', 1, 18, 'cours : BOXE EDUCATIVE CONFIRMES + GRAPPLING'),
  ('portet', 'mma-sol', 2, 12, 'cours : PREPARATION PHYSIQUE + MMA'),
  ('portet', 'mma-sol', 2, 13, 'cours : PREPARATION PHYSIQUE + MMA'),
  ('portet', 'mma-sol', 2, 16, 'cours : ANGLAISE LOISIRS'),
  ('portet', 'mma-sol', 2, 18, 'cours : LADY KICK'),
  ('portet', 'mma-sol', 3, 12, 'cours : KICK / K1'),
  ('portet', 'mma-sol', 3, 13, 'cours : KICK / K1'),
  ('portet', 'mma-sol', 3, 14, 'cours : KICK ENFANTS'),
  ('portet', 'mma-sol', 3, 15, 'cours : KICK ADOS + KICK ENFANTS'),
  ('portet', 'mma-sol', 3, 16, 'cours : BOXE EDUCATIVE 7/11ANS + KICK ADOS'),
  ('portet', 'mma-sol', 3, 17, 'cours : BOXE EDUCATIVE 12/16ANS + MMA ADOS'),
  ('portet', 'mma-sol', 3, 18, 'cours : BOXING LADY + GRAPPLING'),
  ('portet', 'mma-sol', 4, 12, 'cours : ANGLAISE + GRAPPLING'),
  ('portet', 'mma-sol', 4, 13, 'cours : ANGLAISE + GRAPPLING'),
  ('portet', 'mma-sol', 4, 18, 'cours : LADY KICK'),
  ('portet', 'mma-sol', 5, 12, 'cours : SPARRING ANGLAISE ET KICK + KICK / K1'),
  ('portet', 'mma-sol', 5, 13, 'cours : SPARRING ANGLAISE ET KICK + KICK / K1'),
  ('portet', 'mma-sol', 5, 18, 'cours : BOXE AMATEURS ET PROS + GRAPPLING'),
  ('portet', 'mma-sol', 6, 10, 'cours : BOXE FRANCAISE + KICK ENFANTS'),
  ('portet', 'mma-sol', 6, 11, 'cours : PREPARATION PHYSIQUE + KICK ADOS + BOXE FRANCAISE + KICK ENFANTS'),
  ('portet', 'mma-sol', 6, 12, 'cours : ANGLAISE + PREPARATION PHYSIQUE + KICK ADOS + MMA'),
  ('portet', 'mma-sol', 6, 13, 'cours : ANGLAISE + MMA'),
  ('portet', 'mma-sol', 6, 14, 'cours : GRAPPLING'),
  ('portet', 'mma-sol', 6, 15, 'cours : BABY BOXE 4/6 ANS + MMA ADOS'),
  ('portet', 'mma-sol', 6, 16, 'cours : BOXE EDUCATIVE 7/11ANS'),
  ('portet', 'mma-sol', 6, 17, 'cours : BOXE EDUCATIVE 12/16ANS'),
  ('ramonville', 'salle', 1, 12, 'cours : BOXING CAMP'),
  ('ramonville', 'salle', 1, 13, 'cours : BOXING CAMP'),
  ('ramonville', 'salle', 1, 18, 'cours : LADY PUNCH + BOXE PIEDS POINGS'),
  ('ramonville', 'salle', 2, 12, 'cours : ANGLAISE'),
  ('ramonville', 'salle', 2, 13, 'cours : ANGLAISE'),
  ('ramonville', 'salle', 2, 18, 'cours : GRAPPLING'),
  ('ramonville', 'salle', 3, 12, 'cours : BOXING CAMP'),
  ('ramonville', 'salle', 3, 13, 'cours : BOXING CAMP'),
  ('ramonville', 'salle', 3, 15, 'cours : BOXE EDUCATIVE 7/11 ANS'),
  ('ramonville', 'salle', 3, 16, 'cours : BOXE EDUCATIVE 12/16 ANS'),
  ('ramonville', 'salle', 3, 18, 'cours : BOXE ANGLAISE 18H45/20H15'),
  ('ramonville', 'salle', 4, 12, 'cours : BOXE PIEDS POINGS'),
  ('ramonville', 'salle', 4, 13, 'cours : BOXE PIEDS POINGS'),
  ('ramonville', 'salle', 4, 18, 'cours : BOXING CAMP'),
  ('ramonville', 'salle', 5, 12, 'cours : ANGLAISE'),
  ('ramonville', 'salle', 5, 13, 'cours : ANGLAISE'),
  ('ramonville', 'salle', 5, 18, 'cours : LADY PUNCH + BOXE PIEDS POINGS'),
  ('ramonville', 'salle', 6, 11, 'cours : BOXING CAMP'),
  ('ramonville', 'salle', 6, 14, 'cours : BABY BOXE (3/6ANS)'),
  ('ramonville', 'salle', 6, 15, 'cours : BOXE EDUCATIVE 7/11 ANS'),
  ('ramonville', 'salle', 6, 16, 'cours : BOXE EDUCATIVE 12/16 ANS'),
  ('st-cyprien', 'salle', 1, 12, 'cours : BOXING CAMP'),
  ('st-cyprien', 'salle', 1, 13, 'cours : BOXING CAMP'),
  ('st-cyprien', 'salle', 1, 18, 'cours : BOXING CAMP'),
  ('st-cyprien', 'salle', 2, 12, 'cours : BOXE THAI/ K1'),
  ('st-cyprien', 'salle', 2, 13, 'cours : BOXE THAI/ K1'),
  ('st-cyprien', 'salle', 2, 18, 'cours : LADY PUNCH'),
  ('st-cyprien', 'salle', 3, 12, 'cours : ANGLAISE'),
  ('st-cyprien', 'salle', 3, 13, 'cours : ANGLAISE'),
  ('st-cyprien', 'salle', 3, 15, 'cours : BOXE EDUCATIVE 7/11 ANS'),
  ('st-cyprien', 'salle', 3, 16, 'cours : BOXE EDUCATIVE 12/16 ANS'),
  ('st-cyprien', 'salle', 3, 17, 'cours : BOXE EDUCATIVE COMPÉTITEURS'),
  ('st-cyprien', 'salle', 3, 18, 'cours : BOXE EDUCATIVE COMPÉTITEURS + HYROX'),
  ('st-cyprien', 'salle', 4, 12, 'cours : BOXE THAI/ K1'),
  ('st-cyprien', 'salle', 4, 13, 'cours : BOXE THAI/ K1'),
  ('st-cyprien', 'salle', 4, 18, 'cours : LADY PUNCH'),
  ('st-cyprien', 'salle', 5, 12, 'cours : ANGLAISE'),
  ('st-cyprien', 'salle', 5, 13, 'cours : ANGLAISE'),
  ('st-cyprien', 'salle', 5, 18, 'cours : BOXING CAMP'),
  ('st-cyprien', 'salle', 6, 11, 'cours : BOXING CAMP'),
  ('st-cyprien', 'salle', 6, 14, 'cours : BABY BOXE (3/6ANS)'),
  ('st-cyprien', 'salle', 6, 15, 'cours : BOXE EDUCATIVE 7/11 ANS'),
  ('st-cyprien', 'salle', 6, 16, 'cours : BOXE EDUCATIVE 12/16 ANS'),
  ('st-cyprien', 'salle', 6, 17, 'cours : BOXE EDUCATIVE COMPÉTITEURS'),
  ('st-cyprien', 'salle', 6, 18, 'cours : BOXE EDUCATIVE COMPÉTITEURS + BOXE THAI/ K1 18H/20H')
on conflict (club_id, space_id, isodow, start_hour)
do update set is_active = true,
  reason = case when coach_slot_block_rules.reason = 'educative' then coach_slot_block_rules.reason else excluded.reason end;
